Update wdio.conf.js
Change "chrome" to "firefox" because with chrome a test fails:
1) ERROR   Not the page "Selenium Standalone Service"  ::
element not visible
running chrome
Error: An element command could not be completed because the element is not visible on the page.
    at Context.<anonymous> (test/specs/TestOne.js:15:11)
    at new Promise (node_modules/core-js/library/modules/es6.promise.js:177:7)
    at elementIdClick("0.07840463656729035-2") - click.js:20:22